/run/initialize
/control/verbose  0
/run/verbose 0
/event/verbose    0
/tracking/verbose 0


/gps/particle gamma
/gps/pos/type Beam
/gps/ene/type Mono
/gps/ene/mono 2000 eV
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 1 0
/gps/pos/radius 6.25 mm
/gps/pos/centre 0. 0. 0. cm
/gps/direction 0 0 -1

###################################################

/run/beamOn 500000000
